<?php

namespace App\Repository;

use App\Entity\Client;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Client::class);
    }

	public function getNextNumClient() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:Client c ORDER BY c.numClient desc')
	        ->setMaxResults(1);
	        
	    try {
	    	$client = $query->getSingleResult();
	    	if ($client != null) {
	    		return $client->getNumClient() + 1;
	    	} else {
	        	return 0;
	        } 
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}

	public function getLastAdded() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:Client c ORDER BY c.id desc')
	        ->setMaxResults(3);
	        
	    try {
	    	return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return 1;
	    }
	}
}
