<?php

namespace App\Repository;

use App\Entity\Commande;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Commande::class);
    }

	public function getNextNumFactu() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:Commande c ORDER BY c.numFactu desc')
	        ->setMaxResults(1);
	        
	    try {
	    	$commande = $query->getSingleResult();
	    	if ($commande != null) {
	    		return $commande->getNumFactu() + 1;
	    	} else {
	        	return 1;
	        } 
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return 1;
	    }
	}

	public function getLastAdded() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:Commande c ORDER BY c.id desc')
	        ->setMaxResults(3);
	        
	    try {
	    	return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return 1;
	    }
	}

	public function getCommandeToDelivery() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:Commande c WHERE c.toDelivered = 1 AND c.isDelivered = 0');
	        
	    try {
	    	return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}

	public function getNbCommandeToDelivery() {
    	$listCommandes = $this->getCommandeToDelivery();
    	if ($listCommandes != null) {
    		return count($listCommandes);
    	} else {
        	return 0;
        } 
	}

	public function getCommandesByYearMonthDay($month, $year) {
		$emConfig = $this->getEntityManager()->getConfiguration();
	    $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
	    $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');

	    $qb = $this->createQueryBuilder('c');
	    $qb->select('c')
	       ->where('YEAR(c.dateFactu) = :year')
	       ->andWhere('MONTH(c.dateFactu) = :month');

	    $qb->setParameter('year', $year)
	       ->setParameter('month', $month);

	    $qb->orderBy('c.dateFactu', 'ASC');

	   	$listResult = $qb->getQuery()->getResult();
	    return $listResult;
	}

	public function findAllWithSpecificBdl($bdl) {

	    $qb = $this->createQueryBuilder('c');
	    $qb->select('c')
	       ->where('c.bdl = :bdl');

	    $qb->setParameter('bdl', $bdl);

	    $qb->orderBy('c.dateFactu', 'DESC');

	   	$listResult = $qb->getQuery()->getResult();
	    return $listResult;
	}

	public function findAllOrderByDateFactuDesc() {

	    $qb = $this->createQueryBuilder('c');
	    $qb->select('c');

	    $qb->orderBy('c.dateFactu', 'ASC');

	   	$listResult = $qb->getQuery()->getResult();
	    return $listResult;
	}


	public function getCommandeWithBdlId($id) {
	    $qb = $this->createQueryBuilder('c');
	    $qb->select('c')
	       ->where('c.bdl = :id');

	    $qb->setParameter('id', $id);

	   	$listResult = $qb->getQuery()->getResult();
	    return $listResult;
	}

}
