<?php

namespace App\Repository;

use App\Entity\Type;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Type::class);
    }

	public function findWithCodeAndGrp($code, $grp) {
	    $query = $this->getEntityManager()
	        ->createQuery('
	            SELECT t FROM FactuAppBundle:Type t
	            WHERE t.grp = :grp
	            	AND t.code = :code'
	        )->setParameters(array(
			    'grp' => $grp,
			    'code'  => $code
			));
	        
	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
